require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrowsesController do

  # This should return the minimal set of attributes required to create a valid
  # Browse. As you add validations to Browse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrowsesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all browses as @browses" do
      browse = Browse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:browses).should eq([browse])
    end
  end

  describe "GET show" do
    it "assigns the requested browse as @browse" do
      browse = Browse.create! valid_attributes
      get :show, {:id => browse.to_param}, valid_session
      assigns(:browse).should eq(browse)
    end
  end

  describe "GET new" do
    it "assigns a new browse as @browse" do
      get :new, {}, valid_session
      assigns(:browse).should be_a_new(Browse)
    end
  end

  describe "GET edit" do
    it "assigns the requested browse as @browse" do
      browse = Browse.create! valid_attributes
      get :edit, {:id => browse.to_param}, valid_session
      assigns(:browse).should eq(browse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Browse" do
        expect {
          post :create, {:browse => valid_attributes}, valid_session
        }.to change(Browse, :count).by(1)
      end

      it "assigns a newly created browse as @browse" do
        post :create, {:browse => valid_attributes}, valid_session
        assigns(:browse).should be_a(Browse)
        assigns(:browse).should be_persisted
      end

      it "redirects to the created browse" do
        post :create, {:browse => valid_attributes}, valid_session
        response.should redirect_to(Browse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved browse as @browse" do
        # Trigger the behavior that occurs when invalid params are submitted
        Browse.any_instance.stub(:save).and_return(false)
        post :create, {:browse => { "user" => "invalid value" }}, valid_session
        assigns(:browse).should be_a_new(Browse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Browse.any_instance.stub(:save).and_return(false)
        post :create, {:browse => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested browse" do
        browse = Browse.create! valid_attributes
        # Assuming there are no other browses in the database, this
        # specifies that the Browse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Browse.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => browse.to_param, :browse => { "user" => "" }}, valid_session
      end

      it "assigns the requested browse as @browse" do
        browse = Browse.create! valid_attributes
        put :update, {:id => browse.to_param, :browse => valid_attributes}, valid_session
        assigns(:browse).should eq(browse)
      end

      it "redirects to the browse" do
        browse = Browse.create! valid_attributes
        put :update, {:id => browse.to_param, :browse => valid_attributes}, valid_session
        response.should redirect_to(browse)
      end
    end

    describe "with invalid params" do
      it "assigns the browse as @browse" do
        browse = Browse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Browse.any_instance.stub(:save).and_return(false)
        put :update, {:id => browse.to_param, :browse => { "user" => "invalid value" }}, valid_session
        assigns(:browse).should eq(browse)
      end

      it "re-renders the 'edit' template" do
        browse = Browse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Browse.any_instance.stub(:save).and_return(false)
        put :update, {:id => browse.to_param, :browse => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested browse" do
      browse = Browse.create! valid_attributes
      expect {
        delete :destroy, {:id => browse.to_param}, valid_session
      }.to change(Browse, :count).by(-1)
    end

    it "redirects to the browses list" do
      browse = Browse.create! valid_attributes
      delete :destroy, {:id => browse.to_param}, valid_session
      response.should redirect_to(browses_url)
    end
  end

end
