require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SearchWordsController do

  # This should return the minimal set of attributes required to create a valid
  # SearchWord. As you add validations to SearchWord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SearchWordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all search_words as @search_words" do
      search_word = SearchWord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:search_words).should eq([search_word])
    end
  end

  describe "GET show" do
    it "assigns the requested search_word as @search_word" do
      search_word = SearchWord.create! valid_attributes
      get :show, {:id => search_word.to_param}, valid_session
      assigns(:search_word).should eq(search_word)
    end
  end

  describe "GET new" do
    it "assigns a new search_word as @search_word" do
      get :new, {}, valid_session
      assigns(:search_word).should be_a_new(SearchWord)
    end
  end

  describe "GET edit" do
    it "assigns the requested search_word as @search_word" do
      search_word = SearchWord.create! valid_attributes
      get :edit, {:id => search_word.to_param}, valid_session
      assigns(:search_word).should eq(search_word)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SearchWord" do
        expect {
          post :create, {:search_word => valid_attributes}, valid_session
        }.to change(SearchWord, :count).by(1)
      end

      it "assigns a newly created search_word as @search_word" do
        post :create, {:search_word => valid_attributes}, valid_session
        assigns(:search_word).should be_a(SearchWord)
        assigns(:search_word).should be_persisted
      end

      it "redirects to the created search_word" do
        post :create, {:search_word => valid_attributes}, valid_session
        response.should redirect_to(SearchWord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved search_word as @search_word" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchWord.any_instance.stub(:save).and_return(false)
        post :create, {:search_word => { "user" => "invalid value" }}, valid_session
        assigns(:search_word).should be_a_new(SearchWord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchWord.any_instance.stub(:save).and_return(false)
        post :create, {:search_word => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested search_word" do
        search_word = SearchWord.create! valid_attributes
        # Assuming there are no other search_words in the database, this
        # specifies that the SearchWord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SearchWord.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => search_word.to_param, :search_word => { "user" => "" }}, valid_session
      end

      it "assigns the requested search_word as @search_word" do
        search_word = SearchWord.create! valid_attributes
        put :update, {:id => search_word.to_param, :search_word => valid_attributes}, valid_session
        assigns(:search_word).should eq(search_word)
      end

      it "redirects to the search_word" do
        search_word = SearchWord.create! valid_attributes
        put :update, {:id => search_word.to_param, :search_word => valid_attributes}, valid_session
        response.should redirect_to(search_word)
      end
    end

    describe "with invalid params" do
      it "assigns the search_word as @search_word" do
        search_word = SearchWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => search_word.to_param, :search_word => { "user" => "invalid value" }}, valid_session
        assigns(:search_word).should eq(search_word)
      end

      it "re-renders the 'edit' template" do
        search_word = SearchWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => search_word.to_param, :search_word => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested search_word" do
      search_word = SearchWord.create! valid_attributes
      expect {
        delete :destroy, {:id => search_word.to_param}, valid_session
      }.to change(SearchWord, :count).by(-1)
    end

    it "redirects to the search_words list" do
      search_word = SearchWord.create! valid_attributes
      delete :destroy, {:id => search_word.to_param}, valid_session
      response.should redirect_to(search_words_url)
    end
  end

end
